### ISSUE TITLE
AS A group owner I WANT TO invite users to a group  

### ISSUE THREAD

**Issue by micdra01** [d4211n9/PayUp#3]
Frontend:
- [x] Invite members component

Backend:
- [x] Search users endpoint (email, name, phone no.)

Database:
- [x] Invitation table (date, Sender, receiver, group)

Test: 
- [x] Search
- [x] Invitation

**Comment by micdra01** [comment]
Husk feedback om søgning fra BuildABox https://github.com/d4211n9/BuildABox/issues/31
og husk page size / no.

**Comment by JennyTromTheBlock** [comment]
har lavet ændringer så det følger vores konventioner... Bruger using i stedet for finally og bruger middelware og toasts rigtigt.

**Comment by JennyTromTheBlock** [comment]
review notes.
Husk at bruge using i repo og ikke finally. (så vores kode følger samme syntax)
husk at bruge vores indbyggede toasts i frontend,
begge dele er rettet 

mangler frontend: 
skal kunne sende en tom search string fra frontend, pt fejler den nå stringen er tom (hvis jeg indsætter et bogstav virker det)
